services:
  nginx:
    image: nginx:latest
    container_name: flea_market_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - flea_market_network
    restart: always

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    container_name: flea_market_php
    restart: always
    networks:
      - flea_market_network

  mysql:
    image: mysql:8.0.26
    container_name: flea_market_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flea_market_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - flea_market_network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: flea_market_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: always
    networks:
      - flea_market_network

  mailhog:
    image: mailhog/mailhog
    container_name: flea_market_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
    networks:
      - flea_market_network

networks:
  flea_market_network:
    driver: bridge
