services:
  php:
    working_dir: /var/www
    env_file:
      - src/.env
    volumes:
      - ./src:/var/www/
    depends_on:
      - mysql

  mysql:
    env_file:
      - src/.env

  phpmyadmin:
    depends_on:
      - mysql
    env_file:
      - src/.env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=pass
